bill = input('Welcome to the tip calculator!\n' 'what is the the total bill?')
tip = input('How much tip would you like to give? 10,12 or 15?')
people = input('How many people to spilt the bill?')
total =  (float(bill) * ((float(tip)+100)/100))/int(people)
print(f'Each person should pay: ${total:.2f}')